@extends('template.auth.master')
@section('title', 'Registrasi Tenant Vokasi')

@section('body')
<body>
    <div class="min-h-screen items-center justify-center bg-gray-50 py-8 md:px-60">
        <div>
            <div class="mb-10">
                <img class="mx-auto h-auto md:w-1/4 w-1/2" src="{{ asset('assets/images/icon_title.png') }}"
                    alt="Workflow">
                <h2 class="text-center text-3xl font-extrabold text-gray-900">
                    SINTEVO
                </h2>
                <h2 class="text-center text-2xl font-light text-gray-900">
                    Sistem Informasi Tenant Vokasi
                </h2>
            </div>
            <div class="md:grid md:gap-6">
                <div class="mt-5 md:mt-0 md:col-span-2 animate__animated" id="form_regis">
                    <form action="{{ route('signup2') }}" method="POST" id="form_register">
                        @csrf
                        <div class="shadow sm:rounded-md sm:overflow-hidden">
                            <div class="px-4 py-5 bg-white space-y-6 sm:p-6">
                                <h2 class="text-2xl font-light text-gray-900">
                                    Formulir Registrasi Tenant Vokasi
                                </h2>
                                <div class="" aria-hidden="true">
                                    <div class="">
                                        <div class="border-t border-gray-200"></div>
                                    </div>
                                </div>

                                <div class="grid grid-cols-3 gap-6">
                                    <div class="col-span-6 sm:col-span-3">
                                        <label for="status"
                                            class="block text-sm font-medium text-gray-700">Status*</label>
                                        <select id="status" name="status" onchange="checkValue(this); prodiSelect(this)"
                                            class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-lightBlue-500 focus:border-lightBlue-500 sm:text-sm">
                                            <option disabled selected>Pilih Status</option>
                                            @foreach ($status as $s)
                                                <option value="{{ $s->id_status }}">{{ $s->jenis_status }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div id="prodi-select" data-visible="false">
                                    {{-- Generated by JS --}}
                                </div>

                                <div class="grid grid-cols-3 gap-6">
                                    <div class="col-span-6 sm:col-span-3">
                                        <label for="kategori" class="block text-sm font-medium text-gray-700">Kategori
                                            Usaha*</label>
                                        <select id="kategori" name="kategori" onchange="checkValue(this)"
                                            class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-lightBlue-500 focus:border-lightBlue-500 sm:text-sm">
                                            <option disabled selected>Pilih Kategori Usaha</option>
                                            @foreach ($kategori as $k)
                                                <option value="{{ $k->id_kategori }}">{{ $k->nama_kategori }}
                                                </option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>

                                <div class="col-span-6 sm:col-span-4">
                                    <label for="nama_brand" class="block text-sm font-medium text-gray-700">Nama Brand /
                                        Usaha*</label>
                                    <input required type="text" name="nama_brand" id="nama_brand"
                                        placeholder="Contoh: Aftermeet Academy" oninput="checkValue(this)"
                                        class="mt-1 focus:ring-lightBlue-500 focus:border-lightBlue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                </div>

                                <div>
                                    <label for="deskripsi" class="block text-sm font-medium text-gray-700">
                                        Deskripsi Usaha*
                                    </label>
                                    <div class="mt-1">
                                        <textarea id="deskripsi" name="deskripsi" rows="5" oninput="checkValue(this)"
                                            class="shadow-sm focus:ring-lightBlue-500 focus:border-lightBlue-500 mt-1 block w-full sm:text-sm border-gray-300 rounded-md"
                                            placeholder="Deskripsikan Usaha / Produk / Layanan Usaha Anda"></textarea>
                                    </div>
                                </div>

                                <div class="col-span-6 sm:col-span-4">
                                    <label for="alamat" class="block text-sm font-medium text-gray-700">Alamat*</label>
                                    <input required type="text" name="alamat" id="alamat"
                                        placeholder="Masukkan Alamat Usaha Anda" oninput="checkValue(this)"
                                        class="mt-1 focus:ring-lightBlue-500 focus:border-lightBlue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                </div>

                                <div class="col-span-6 sm:col-span-4">
                                    <label for="nama_ketua" class="block text-sm font-medium text-gray-700">Nama
                                        Ketua*</label>
                                    <input required type="text" name="nama_ketua" id="nama_ketua"
                                        placeholder="Masukkan Nama Lengkap Ketua Usaha / Tim" oninput="checkValue(this)"
                                        class="mt-1 focus:ring-lightBlue-500 focus:border-lightBlue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                </div>

                                <div class="col-span-6 sm:col-span-4">
                                    <label for="no_whatsapp" class="block text-sm font-medium text-gray-700">Nomor
                                        WhatsApp*</label>
                                    <input required type="text" name="no_whatsapp" id="no_whatsapp"
                                        placeholder="Masukkan Nomor WhatsApp Ketua Usaha / Tim"
                                        oninput="checkValue(this);regexNumOnly(this)"
                                        class="mt-1 focus:ring-lightBlue-500 focus:border-lightBlue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                </div>

                                <div class="col-span-6 sm:col-span-4">
                                    <label for="website" class="block text-sm font-medium text-gray-700">
                                        Website
                                    </label>
                                    <div class="mt-1 flex rounded-md shadow-sm">
                                        <span
                                            class="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 text-sm">
                                            http://
                                        </span>
                                        <input type="text" name="website" id="website"
                                            class="focus:ring-lightBlue-500 focus:border-lightBlue-500 flex-1 block w-full rounded-none rounded-r-md sm:text-sm border-gray-300"
                                            placeholder="www.example.com" oninput="checkValue()">
                                    </div>
                                    <p class="text-xs italic md ml-2 text-gray-300">
                                        opsional
                                    </p>
                                </div>

                                <div class="col-span-6 sm:col-span-4">
                                    <label for="instagram"
                                        class="block text-sm font-medium text-gray-700">Instagram (Gunakan '@')</label>
                                    <input type="text" name="instagram" id="instagram"
                                        placeholder="Masukkan Username Instagram Usaha (Kosongkan Jika Tidak Ada), ex: @example"
                                        oninput="checkValue()"
                                        class="mt-1 focus:ring-lightBlue-500 focus:border-lightBlue-500 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md">
                                    <p class="text-xs italic md ml-2 text-gray-300">
                                        opsional
                                    </p>
                                </div>
                                <p class="mt-2 text-sm text-gray-500">
                                    Keterangan: *Wajib Diisi
                                </p>

                            </div>
                            <div class="px-4 py-3 bg-gray-50 flex justify-between sm:px-6">
                                <p class="text-center text-sm text-gray-600">
                                    Sudah punya akun ?
                                    <a href="{{ route('login') }}" class="font-medium text-lightBlue-600 hover:text-lightBlue-500">
                                        Login disini
                                    </a>
                                </p>
                                <button type="button" id="btn-continue" disabled
                                    class="disabled:opacity-50 disabled:cursor-not-allowed inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-lightBlue-600 hover:bg-lightBlue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-lightBlue-500">
                                    Continue
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>
@endsection

@section('script')
<script src="{{ asset('js/app.js') }}"></script>
<script src="{{ asset('js/core/jquery-3.5.1.min.js') }}"></script>
<script src="{{ asset('js/myscript.js') }}"></script>

</html>
@endsection

